# Site settings
title: Justin Wuetcher
email: me@justinwuetcher.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jwuetcher.github.io" # the base hostname & protocol for your site
twitter_username: jwuetcher
github_username:  jwuetcher
linkedin_username:  justinwuetcher

# Build settings
markdown: kramdown



port: 5000
