# Site settings
title: My Portfolio
email: me@justinwuetcher.com
description: "Justin Wuetcher's Portfolio"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/justinwuetcher
  - title: github
    url: http://github.com/jwuetcher
  - title: envelope
    url: mailto:me@justinwuetcher.com

# Postal address (add as many lines as necessary)
address:
  - line: W. North St.
  - line: Baltimore, MD 21218

# Build settings
markdown: kramdown
permalink: pretty
